docker-prod:
  stage: docker-test
  image: docker:stable
  script:
    - docker info
    - docker ps
  <<: *runner_prod_tags
  only:
    - master

cache-npm-test-prod:
  stage: cache-npm-test
  cache:
    paths:
    - node_modules/
  image: node:4.2.2
  script:
   - npm install
  <<: *runner_prod_tags
  only:
    - master

no-cache-npm-test-prod:
  stage: cache-npm-test
  image: node:4.2.2
  script:
   - npm install
  <<: *runner_prod_tags
  only:
    - master
